---
- name: Ensure dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_dependencies }}"

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins.rpm"
  when: jenkins_version != 'latest'

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins.rpm"
  register: specific_version

- name: Install our specific version of Jenkins.
  package:
    name: "/tmp/jenkins.rpm"
    state: installed
  when: specific_version.stat.exists

- name: Validate Jenkins is installed and register package name.
  package:
    name: jenkins
    state: present
  when: not specific_version.stat.exists

- name: Install Jenkins from repository.
  package:
    name: jenkins
    state: installed
  when: jenkins_version == 'latest' 

- name: Update jenkins user
  user:
    name: jenkins
    uid: 1000
    groups: root
    append: yes

- name: Install dumb init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/bin/dumb-init
    owner: root
    group: root
    mode: 0775
